### ISSUE TITLE
Unclosed resources?

### ISSUE THREAD

**Issue by MAP94** [jenssegers/php-imagehash#2]
If you hash an image by filename the hash function will create a resource that is never closed.

https://github.com/jenssegers/php-imagehash/blob/master/src/ImageHash.php#L36

	public function hash($resource)
	{
		$resource = is_resource($resource) ? $resource : $this->loadImageResource($resource);
		$hash = $this->implementation->hash($resource);
		return $hash;
	}

**Comment by jenssegers** [comment]
Resources should now be closed in the last commit :)
